# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'double-window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 715)
        MainWindow.setStyleSheet("/* ===== 全局字体和背景 ===== */\n"
"QMainWindow, QDialog {\n"
"    background-color: #f0f2f5; /* 非常浅的灰色背景，比纯白更有质感 */\n"
"    font-family: \"Segoe UI\", \"Microsoft YaHei\", \"Helvetica Neue\", sans-serif; /* 使用更现代的字体 */\n"
"}\n"
"\n"
"/* ===== 视频显示区 ===== */\n"
"#imgDisplayLabel {\n"
"    background-color: #ffffff; /* 纯白背景 */\n"
"    border: 1px solid #dcdfe6; /* 浅灰色边框 */\n"
"    border-radius: 8px; /* 圆角可以大一点，显得更柔和 */\n"
"}\n"
"\n"
"/* ===== 控制面板 (QGroupBox) ===== */\n"
"QGroupBox {\n"
"    background-color: #ffffff; /* 面板背景也是纯白 */\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 8px;\n"
"    margin-top: 25px; /* 给标题留出足够空间 */\n"
"    font-size: 11pt; /* 字体可以稍微大一点 */\n"
"}\n"
"\n"
"/* 控制面板的标题样式 - 标签(Chip)版 */\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    margin-left: 15px;\n"
"    padding: 4px 12px; /* 上下4px, 左右12px的内边距 */\n"
"    \n"
"    /* 关键部分在这里 */\n"
"    background-color: #e8eef8; /* 一个非常淡的蓝色，与主题呼应 */\n"
"    border-radius: 4px; /* 轻微的圆角 */\n"
"    color: #409eff; /* 文字颜色使用主题的主蓝色 */\n"
"    font-weight: bold;\n"
"    font-size: 10pt; /* 可以稍微调整字号 */\n"
"}\n"
"\n"
"/* ===== 面板内的控件 ===== */\n"
"\n"
"/* 标签样式 (QLabel) */\n"
"QGroupBox QLabel {\n"
"    color: #606266; /* 次要文字用灰色 */\n"
"    background-color: transparent;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"/* 输入框样式 (QLineEdit) */\n"
"QGroupBox QLineEdit {\n"
"    background-color: #fdfdfe;\n"
"    color: #303133; /* 主要文字用深灰色 */\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-size: 10pt;\n"
"}\n"
"QGroupBox QLineEdit:focus {\n"
"    border: 1px solid #409eff; /* 焦点颜色使用明亮的蓝色 */\n"
"    background-color: #ffffff;\n"
"}\n"
"QGroupBox QLineEdit:disabled {\n"
"    background-color: #f5f7fa; /* 禁用状态的颜色 */\n"
"    color: #c0c4cc;\n"
"}\n"
"\n"
"\n"
"/* ===== 按钮样式 (QPushButton) ===== */\n"
"\n"
"/* 默认按钮样式 (蓝色) */\n"
"QGroupBox QPushButton {\n"
"    background-color: #409eff; /* 主按钮颜色 - 亮蓝色 */\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 20px;\n"
"    border-radius: 4px;\n"
"    font-size: 10pt;\n"
"    font-weight: 500;\n"
"}\n"
"QGroupBox QPushButton:hover {\n"
"    background-color: #66b1ff; /* 悬停时更亮 */\n"
"}\n"
"QGroupBox QPushButton:pressed {\n"
"    background-color: #3a8ee6; /* 按下时更深 */\n"
"}\n"
"\n"
"\n"
"/* \"继续\" 按钮的特定样式 (绿色) */\n"
"#Continue_Button {\n"
"    background-color: #67c23a; /* 成功的绿色 */\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"#Continue_Button:hover {\n"
"    background-color: #85ce61;\n"
"}\n"
"#Continue_Button:pressed {\n"
"    background-color: #5daf34;\n"
"}\n"
"\n"
"\n"
"/* \"暂停\" 按钮的特定样式 (红色) */\n"
"#Stop_Button {\n"
"    background-color: #f56c6c; /* 警告的红色 */\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"#Stop_Button:hover {\n"
"    background-color: #f78989;\n"
"}\n"
"#Stop_Button:pressed {\n"
"    background-color: #f35252;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 30, 781, 621))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.imgDisplayLabel = QtWidgets.QLabel(self.page)
        self.imgDisplayLabel.setGeometry(QtCore.QRect(50, 30, 656, 369))
        self.imgDisplayLabel.setStyleSheet("QLabel {\n"
"    min-width: 640px;\n"
"    min-height: 360px;\n"
"    max-width: 1920px;  /* 按比例计算：360 * (1920/640) = 1080 */\n"
"    max-height: 1080px;\n"
"}")
        self.imgDisplayLabel.setScaledContents(True)
        self.imgDisplayLabel.setObjectName("imgDisplayLabel")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(80, 410, 571, 191))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.show_encircle_rate_edit = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_encircle_rate_edit.setFont(font)
        self.show_encircle_rate_edit.setReadOnly(True)
        self.show_encircle_rate_edit.setObjectName("show_encircle_rate_edit")
        self.gridLayout.addWidget(self.show_encircle_rate_edit, 0, 5, 1, 1)
        self.Obs_Num_LineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Obs_Num_LineEdit.sizePolicy().hasHeightForWidth())
        self.Obs_Num_LineEdit.setSizePolicy(sizePolicy)
        self.Obs_Num_LineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Obs_Num_LineEdit.setObjectName("Obs_Num_LineEdit")
        self.gridLayout.addWidget(self.Obs_Num_LineEdit, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 4, 1, 1)
        self.Pursuer_Num_Label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pursuer_Num_Label_2.sizePolicy().hasHeightForWidth())
        self.Pursuer_Num_Label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Pursuer_Num_Label_2.setFont(font)
        self.Pursuer_Num_Label_2.setObjectName("Pursuer_Num_Label_2")
        self.gridLayout.addWidget(self.Pursuer_Num_Label_2, 0, 0, 1, 1)
        self.Obstacle_Num_Label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Obstacle_Num_Label_4.sizePolicy().hasHeightForWidth())
        self.Obstacle_Num_Label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Obstacle_Num_Label_4.setFont(font)
        self.Obstacle_Num_Label_4.setObjectName("Obstacle_Num_Label_4")
        self.gridLayout.addWidget(self.Obstacle_Num_Label_4, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.env_length_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.env_length_label.sizePolicy().hasHeightForWidth())
        self.env_length_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.env_length_label.setFont(font)
        self.env_length_label.setObjectName("env_length_label")
        self.gridLayout.addWidget(self.env_length_label, 1, 0, 1, 1)
        self.env_width_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.env_width_label.sizePolicy().hasHeightForWidth())
        self.env_width_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.env_width_label.setFont(font)
        self.env_width_label.setObjectName("env_width_label")
        self.gridLayout.addWidget(self.env_width_label, 1, 2, 1, 1)
        self.Pursuer_Num_LineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pursuer_Num_LineEdit.sizePolicy().hasHeightForWidth())
        self.Pursuer_Num_LineEdit.setSizePolicy(sizePolicy)
        self.Pursuer_Num_LineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.Pursuer_Num_LineEdit.setText("")
        self.Pursuer_Num_LineEdit.setObjectName("Pursuer_Num_LineEdit")
        self.gridLayout.addWidget(self.Pursuer_Num_LineEdit, 0, 1, 1, 1)
        self.env_width_LineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.env_width_LineEdit.sizePolicy().hasHeightForWidth())
        self.env_width_LineEdit.setSizePolicy(sizePolicy)
        self.env_width_LineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.env_width_LineEdit.setObjectName("env_width_LineEdit")
        self.gridLayout.addWidget(self.env_width_LineEdit, 1, 3, 1, 1)
        self.show_time_edit = QtWidgets.QLineEdit(self.groupBox)
        self.show_time_edit.setReadOnly(True)
        self.show_time_edit.setObjectName("show_time_edit")
        self.gridLayout.addWidget(self.show_time_edit, 1, 5, 1, 1)
        self.env_length_LineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.env_length_LineEdit.sizePolicy().hasHeightForWidth())
        self.env_length_LineEdit.setSizePolicy(sizePolicy)
        self.env_length_LineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.env_length_LineEdit.setObjectName("env_length_LineEdit")
        self.gridLayout.addWidget(self.env_length_LineEdit, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Stop_Button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stop_Button.sizePolicy().hasHeightForWidth())
        self.Stop_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.Stop_Button.setFont(font)
        self.Stop_Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(252, 1, 7);  /* 绿色背景（可改颜色码） */\n"
"    color: white;               /* 文字白色 */\n"
"    font-size: 14px;            /* 文字大小 */\n"
"    border: none;               /* 去掉边框 */\n"
"    padding: 5px 10px;          /* 按钮内边距 */\n"
"}")
        self.Stop_Button.setObjectName("Stop_Button")
        self.gridLayout_2.addWidget(self.Stop_Button, 0, 0, 1, 1)
        self.Continue_Button = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.Continue_Button.setFont(font)
        self.Continue_Button.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;  /* 绿色背景（可改颜色码） */\n"
"    color: white;               /* 文字白色 */\n"
"    font-size: 14px;            /* 文字大小 */\n"
"    border: none;               /* 去掉边框 */\n"
"    padding: 5px 10px;          /* 按钮内边距 */\n"
"}")
        self.Continue_Button.setObjectName("Continue_Button")
        self.gridLayout_2.addWidget(self.Continue_Button, 0, 1, 1, 1)
        self.ApplyButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ApplyButton.sizePolicy().hasHeightForWidth())
        self.ApplyButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.ApplyButton.setFont(font)
        self.ApplyButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 255);  /* 绿色背景（可改颜色码） */\n"
"    color: white;               /* 文字白色 */\n"
"    font-size: 14px;            /* 文字大小 */\n"
"    border: none;               /* 去掉边框 */\n"
"    padding: 5px 10px;          /* 按钮内边距 */\n"
"}")
        self.ApplyButton.setObjectName("ApplyButton")
        self.gridLayout_2.addWidget(self.ApplyButton, 0, 3, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(8)
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.energy_pursuer_graph_widget = PlotWidget(self.page_2)
        self.energy_pursuer_graph_widget.setGeometry(QtCore.QRect(30, 20, 731, 231))
        self.energy_pursuer_graph_widget.setStyleSheet("background-color: white;")
        self.energy_pursuer_graph_widget.setObjectName("energy_pursuer_graph_widget")
        self.scrollarea_pies = QtWidgets.QScrollArea(self.page_2)
        self.scrollarea_pies.setGeometry(QtCore.QRect(30, 259, 731, 341))
        self.scrollarea_pies.setWidgetResizable(True)
        self.scrollarea_pies.setObjectName("scrollarea_pies")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 729, 339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollarea_pies.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.obs_num_baseline_lineedit = QtWidgets.QLineEdit(self.page_3)
        self.obs_num_baseline_lineedit.setGeometry(QtCore.QRect(310, 500, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.obs_num_baseline_lineedit.setFont(font)
        self.obs_num_baseline_lineedit.setReadOnly(True)
        self.obs_num_baseline_lineedit.setObjectName("obs_num_baseline_lineedit")
        self.init_min_dist_baseline_lineedit = QtWidgets.QLineEdit(self.page_3)
        self.init_min_dist_baseline_lineedit.setGeometry(QtCore.QRect(130, 500, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.init_min_dist_baseline_lineedit.setFont(font)
        self.init_min_dist_baseline_lineedit.setReadOnly(True)
        self.init_min_dist_baseline_lineedit.setObjectName("init_min_dist_baseline_lineedit")
        self.env_length_baseline_lineedit = QtWidgets.QLineEdit(self.page_3)
        self.env_length_baseline_lineedit.setGeometry(QtCore.QRect(480, 460, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.env_length_baseline_lineedit.setFont(font)
        self.env_length_baseline_lineedit.setReadOnly(True)
        self.env_length_baseline_lineedit.setObjectName("env_length_baseline_lineedit")
        self.env_width_baseline_lineedit = QtWidgets.QLineEdit(self.page_3)
        self.env_width_baseline_lineedit.setGeometry(QtCore.QRect(480, 500, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.env_width_baseline_lineedit.setFont(font)
        self.env_width_baseline_lineedit.setReadOnly(True)
        self.env_width_baseline_lineedit.setObjectName("env_width_baseline_lineedit")
        self.baseline_apply_button = QtWidgets.QPushButton(self.page_3)
        self.baseline_apply_button.setGeometry(QtCore.QRect(570, 470, 113, 32))
        self.baseline_apply_button.setObjectName("baseline_apply_button")
        self.baseline_collision_button = QtWidgets.QPushButton(self.page_3)
        self.baseline_collision_button.setGeometry(QtCore.QRect(50, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.baseline_collision_button.setFont(font)
        self.baseline_collision_button.setObjectName("baseline_collision_button")
        self.baseline_time_button = QtWidgets.QPushButton(self.page_3)
        self.baseline_time_button.setGeometry(QtCore.QRect(180, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.baseline_time_button.setFont(font)
        self.baseline_time_button.setObjectName("baseline_time_button")
        self.baseline_success_button = QtWidgets.QPushButton(self.page_3)
        self.baseline_success_button.setGeometry(QtCore.QRect(310, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.baseline_success_button.setFont(font)
        self.baseline_success_button.setObjectName("baseline_success_button")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget_2.setGeometry(QtCore.QRect(50, 50, 631, 401))
        self.stackedWidget_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.baseline_collision = QtWidgets.QLabel(self.page_7)
        self.baseline_collision.setGeometry(QtCore.QRect(0, 10, 581, 381))
        self.baseline_collision.setStyleSheet("")
        self.baseline_collision.setText("")
        self.baseline_collision.setObjectName("baseline_collision")
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.baseline_time = QtWidgets.QLabel(self.page_8)
        self.baseline_time.setGeometry(QtCore.QRect(10, 10, 581, 381))
        self.baseline_time.setStyleSheet("")
        self.baseline_time.setText("")
        self.baseline_time.setObjectName("baseline_time")
        self.stackedWidget_2.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.baseline_success = QtWidgets.QLabel(self.page_9)
        self.baseline_success.setGeometry(QtCore.QRect(10, 10, 581, 381))
        self.baseline_success.setText("")
        self.baseline_success.setObjectName("baseline_success")

        image_path_baseline_collision = "/Users/hujunyan/Desktop/论文部分/基线实验结果图/collision_ratio.png"
        pixmap = QPixmap(image_path_baseline_collision)
        self.baseline_collision.setPixmap(pixmap)
        self.baseline_collision.setScaledContents(True)

        image_path_baseline_time = "/Users/hujunyan/Desktop/论文部分/基线实验结果图/time.png"
        pixmap = QPixmap(image_path_baseline_time)
        self.baseline_time.setPixmap(pixmap)
        self.baseline_time.setScaledContents(True)

        image_path_baseline_success = "/Users/hujunyan/Desktop/论文部分/基线实验结果图/success_rate.png"
        pixmap = QPixmap(image_path_baseline_success)
        self.baseline_success.setPixmap(pixmap)
        self.baseline_success.setScaledContents(True)


        self.stackedWidget_2.addWidget(self.page_9)
        self.env_width_baseline_label = QtWidgets.QLabel(self.page_3)
        self.env_width_baseline_label.setGeometry(QtCore.QRect(430, 500, 40, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.env_width_baseline_label.setFont(font)
        self.env_width_baseline_label.setObjectName("env_width_baseline_label")
        self.Obstacle_Num_baseline_label = QtWidgets.QLabel(self.page_3)
        self.Obstacle_Num_baseline_label.setGeometry(QtCore.QRect(230, 500, 60, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Obstacle_Num_baseline_label.sizePolicy().hasHeightForWidth())
        self.Obstacle_Num_baseline_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Obstacle_Num_baseline_label.setFont(font)
        self.Obstacle_Num_baseline_label.setObjectName("Obstacle_Num_baseline_label")
        self.init_min_dis_baseline_label = QtWidgets.QLabel(self.page_3)
        self.init_min_dis_baseline_label.setGeometry(QtCore.QRect(50, 500, 70, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_min_dis_baseline_label.sizePolicy().hasHeightForWidth())
        self.init_min_dis_baseline_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_min_dis_baseline_label.setFont(font)
        self.init_min_dis_baseline_label.setObjectName("init_min_dis_baseline_label")
        self.pursuer_num_lineedit = QtWidgets.QLineEdit(self.page_3)
        self.pursuer_num_lineedit.setGeometry(QtCore.QRect(310, 460, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pursuer_num_lineedit.setFont(font)
        self.pursuer_num_lineedit.setReadOnly(True)
        self.pursuer_num_lineedit.setObjectName("pursuer_num_lineedit")
        self.exp_num_baseline_lineedit = QtWidgets.QLineEdit(self.page_3)
        self.exp_num_baseline_lineedit.setGeometry(QtCore.QRect(130, 460, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exp_num_baseline_lineedit.setFont(font)
        self.exp_num_baseline_lineedit.setReadOnly(True)
        self.exp_num_baseline_lineedit.setObjectName("exp_num_baseline_lineedit")
        self.pursuers_num_baseline_label = QtWidgets.QLabel(self.page_3)
        self.pursuers_num_baseline_label.setGeometry(QtCore.QRect(230, 460, 60, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pursuers_num_baseline_label.sizePolicy().hasHeightForWidth())
        self.pursuers_num_baseline_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pursuers_num_baseline_label.setFont(font)
        self.pursuers_num_baseline_label.setObjectName("pursuers_num_baseline_label")
        self.exp_num_baseline_label = QtWidgets.QLabel(self.page_3)
        self.exp_num_baseline_label.setGeometry(QtCore.QRect(60, 460, 50, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exp_num_baseline_label.sizePolicy().hasHeightForWidth())
        self.exp_num_baseline_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exp_num_baseline_label.setFont(font)
        self.exp_num_baseline_label.setObjectName("exp_num_baseline_label")
        self.env_length_baseline_label = QtWidgets.QLabel(self.page_3)
        self.env_length_baseline_label.setGeometry(QtCore.QRect(430, 460, 40, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.env_length_baseline_label.setFont(font)
        self.env_length_baseline_label.setObjectName("env_length_baseline_label")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.exp_num_ablation_lineedit = QtWidgets.QLineEdit(self.page_4)
        self.exp_num_ablation_lineedit.setGeometry(QtCore.QRect(160, 490, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exp_num_ablation_lineedit.setFont(font)
        self.exp_num_ablation_lineedit.setReadOnly(True)
        self.exp_num_ablation_lineedit.setObjectName("exp_num_ablation_lineedit")
        self.env_length_abaltion_label = QtWidgets.QLabel(self.page_4)
        self.env_length_abaltion_label.setGeometry(QtCore.QRect(460, 490, 40, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.env_length_abaltion_label.setFont(font)
        self.env_length_abaltion_label.setObjectName("env_length_abaltion_label")
        self.env_length_ablation_lineedit = QtWidgets.QLineEdit(self.page_4)
        self.env_length_ablation_lineedit.setGeometry(QtCore.QRect(510, 490, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.env_length_ablation_lineedit.setFont(font)
        self.env_length_ablation_lineedit.setReadOnly(True)
        self.env_length_ablation_lineedit.setObjectName("env_length_ablation_lineedit")
        self.exp_num_ablation_label = QtWidgets.QLabel(self.page_4)
        self.exp_num_ablation_label.setGeometry(QtCore.QRect(90, 490, 50, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exp_num_ablation_label.sizePolicy().hasHeightForWidth())
        self.exp_num_ablation_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exp_num_ablation_label.setFont(font)
        self.exp_num_ablation_label.setObjectName("exp_num_ablation_label")
        self.env_width_ablation_lineedit = QtWidgets.QLineEdit(self.page_4)
        self.env_width_ablation_lineedit.setGeometry(QtCore.QRect(510, 530, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.env_width_ablation_lineedit.setFont(font)
        self.env_width_ablation_lineedit.setReadOnly(True)
        self.env_width_ablation_lineedit.setObjectName("env_width_ablation_lineedit")
        self.pursuer_num_ablation_label = QtWidgets.QLabel(self.page_4)
        self.pursuer_num_ablation_label.setGeometry(QtCore.QRect(260, 490, 60, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pursuer_num_ablation_label.sizePolicy().hasHeightForWidth())
        self.pursuer_num_ablation_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pursuer_num_ablation_label.setFont(font)
        self.pursuer_num_ablation_label.setObjectName("pursuer_num_ablation_label")
        self.obs_num_ablation_label = QtWidgets.QLabel(self.page_4)
        self.obs_num_ablation_label.setGeometry(QtCore.QRect(260, 530, 60, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.obs_num_ablation_label.sizePolicy().hasHeightForWidth())
        self.obs_num_ablation_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.obs_num_ablation_label.setFont(font)
        self.obs_num_ablation_label.setObjectName("obs_num_ablation_label")
        self.init_min_dist_ablation_lineedit = QtWidgets.QLineEdit(self.page_4)
        self.init_min_dist_ablation_lineedit.setGeometry(QtCore.QRect(160, 530, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.init_min_dist_ablation_lineedit.setFont(font)
        self.init_min_dist_ablation_lineedit.setReadOnly(True)
        self.init_min_dist_ablation_lineedit.setObjectName("init_min_dist_ablation_lineedit")
        self.init_min_dist_ablation_label = QtWidgets.QLabel(self.page_4)
        self.init_min_dist_ablation_label.setGeometry(QtCore.QRect(80, 530, 70, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_min_dist_ablation_label.sizePolicy().hasHeightForWidth())
        self.init_min_dist_ablation_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.init_min_dist_ablation_label.setFont(font)
        self.init_min_dist_ablation_label.setObjectName("init_min_dist_ablation_label")
        self.env_width_ablation_label = QtWidgets.QLabel(self.page_4)
        self.env_width_ablation_label.setGeometry(QtCore.QRect(460, 530, 40, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.env_width_ablation_label.setFont(font)
        self.env_width_ablation_label.setObjectName("env_width_ablation_label")
        self.obs_num_ablation_lineedit = QtWidgets.QLineEdit(self.page_4)
        self.obs_num_ablation_lineedit.setGeometry(QtCore.QRect(340, 530, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.obs_num_ablation_lineedit.setFont(font)
        self.obs_num_ablation_lineedit.setReadOnly(True)
        self.obs_num_ablation_lineedit.setObjectName("obs_num_ablation_lineedit")
        self.pursuer_num_ablation_lineedit_2 = QtWidgets.QLineEdit(self.page_4)
        self.pursuer_num_ablation_lineedit_2.setGeometry(QtCore.QRect(340, 490, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pursuer_num_ablation_lineedit_2.setFont(font)
        self.pursuer_num_ablation_lineedit_2.setReadOnly(True)
        self.pursuer_num_ablation_lineedit_2.setObjectName("pursuer_num_ablation_lineedit_2")
        self.ablation_apply_button = QtWidgets.QPushButton(self.page_4)
        self.ablation_apply_button.setGeometry(QtCore.QRect(590, 500, 113, 32))
        self.ablation_apply_button.setObjectName("ablation_apply_button")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.page_4)
        self.stackedWidget_3.setGeometry(QtCore.QRect(30, 60, 631, 401))
        self.stackedWidget_3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.ablation_collision = QtWidgets.QLabel(self.page_10)
        self.ablation_collision.setGeometry(QtCore.QRect(0, 10, 581, 381))
        self.ablation_collision.setText("")
        self.ablation_collision.setObjectName("ablation_collision")
        self.stackedWidget_3.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.ablation_time = QtWidgets.QLabel(self.page_11)
        self.ablation_time.setGeometry(QtCore.QRect(10, 10, 581, 381))
        self.ablation_time.setText("")
        self.ablation_time.setObjectName("ablation_time")
        self.stackedWidget_3.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.ablation_success = QtWidgets.QLabel(self.page_12)
        self.ablation_success.setGeometry(QtCore.QRect(10, 10, 581, 381))
        self.ablation_success.setText("")
        self.ablation_success.setObjectName("ablation_success")
        self.stackedWidget_3.addWidget(self.page_12)
        self.ablation_collision_button = QtWidgets.QPushButton(self.page_4)
        self.ablation_collision_button.setGeometry(QtCore.QRect(30, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ablation_collision_button.setFont(font)
        self.ablation_collision_button.setObjectName("ablation_collision_button")
        self.ablation_time_button = QtWidgets.QPushButton(self.page_4)
        self.ablation_time_button.setGeometry(QtCore.QRect(160, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ablation_time_button.setFont(font)
        self.ablation_time_button.setObjectName("ablation_time_button")
        self.ablation_success_button = QtWidgets.QPushButton(self.page_4)
        self.ablation_success_button.setGeometry(QtCore.QRect(290, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ablation_success_button.setFont(font)
        self.ablation_success_button.setObjectName("ablation_success_button")

        image_path_ablation_collision = "/Users/hujunyan/Desktop/论文部分/消融实验结果图/collision_ratio.png"
        pixmap = QPixmap(image_path_ablation_collision)
        self.ablation_collision.setPixmap(pixmap)
        self.ablation_collision.setScaledContents(True)

        image_path_ablation_collision = "/Users/hujunyan/Desktop/论文部分/消融实验结果图/time.png"
        pixmap = QPixmap(image_path_ablation_collision)
        self.ablation_time.setPixmap(pixmap)
        self.ablation_time.setScaledContents(True)

        image_path_ablation_collision = "/Users/hujunyan/Desktop/论文部分/消融实验结果图/success_rate.png"
        pixmap = QPixmap(image_path_ablation_collision)
        self.ablation_success.setPixmap(pixmap)
        self.ablation_success.setScaledContents(True)

        self.stackedWidget.addWidget(self.page_4)
        self.simulation_panel = QtWidgets.QPushButton(self.centralwidget)
        self.simulation_panel.setGeometry(QtCore.QRect(10, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.simulation_panel.setFont(font)
        self.simulation_panel.setObjectName("simulation_panel")
        self.action_statistics_panel = QtWidgets.QPushButton(self.centralwidget)
        self.action_statistics_panel.setGeometry(QtCore.QRect(90, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.action_statistics_panel.setFont(font)
        self.action_statistics_panel.setObjectName("action_statistics_panel")
        self.baseline_compare_panel = QtWidgets.QPushButton(self.centralwidget)
        self.baseline_compare_panel.setGeometry(QtCore.QRect(190, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.baseline_compare_panel.setFont(font)
        self.baseline_compare_panel.setObjectName("baseline_compare_panel")
        self.ablation_experiment_panel = QtWidgets.QPushButton(self.centralwidget)
        self.ablation_experiment_panel.setGeometry(QtCore.QRect(290, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ablation_experiment_panel.setFont(font)
        self.ablation_experiment_panel.setObjectName("ablation_experiment_panel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Pursuer_Num_LineEdit, self.Obs_Num_LineEdit)
        MainWindow.setTabOrder(self.Obs_Num_LineEdit, self.env_width_LineEdit)
        MainWindow.setTabOrder(self.env_width_LineEdit, self.show_time_edit)
        MainWindow.setTabOrder(self.show_time_edit, self.show_encircle_rate_edit)
        MainWindow.setTabOrder(self.show_encircle_rate_edit, self.ApplyButton)
        MainWindow.setTabOrder(self.ApplyButton, self.Continue_Button)
        MainWindow.setTabOrder(self.Continue_Button, self.horizontalSlider)
        MainWindow.setTabOrder(self.horizontalSlider, self.Stop_Button)
        MainWindow.setTabOrder(self.Stop_Button, self.simulation_panel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TERL"))
        self.imgDisplayLabel.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "控制面板"))
        self.label.setText(_translate("MainWindow", "生成时间："))
        self.Pursuer_Num_Label_2.setText(_translate("MainWindow", "追捕者数量："))
        self.Obstacle_Num_Label_4.setText(_translate("MainWindow", "障碍物数量："))
        self.label_2.setText(_translate("MainWindow", "围捕率："))
        self.env_length_label.setText(_translate("MainWindow", "环境长："))
        self.env_width_label.setText(_translate("MainWindow", "环境宽："))
        self.Stop_Button.setText(_translate("MainWindow", "暂停"))
        self.Continue_Button.setText(_translate("MainWindow", "继续"))
        self.ApplyButton.setText(_translate("MainWindow", "生成"))
        self.obs_num_baseline_lineedit.setText(_translate("MainWindow", "2"))
        self.init_min_dist_baseline_lineedit.setText(_translate("MainWindow", "15"))
        self.env_length_baseline_lineedit.setText(_translate("MainWindow", "60"))
        self.env_width_baseline_lineedit.setText(_translate("MainWindow", "60"))
        self.baseline_apply_button.setText(_translate("MainWindow", "运行"))
        self.baseline_collision_button.setText(_translate("MainWindow", "碰撞率对比图"))
        self.baseline_time_button.setText(_translate("MainWindow", "时间对比图"))
        self.baseline_success_button.setText(_translate("MainWindow", "成功率对比图"))
        self.env_width_baseline_label.setText(_translate("MainWindow", "环境宽："))
        self.Obstacle_Num_baseline_label.setText(_translate("MainWindow", "障碍物数量："))
        self.init_min_dis_baseline_label.setText(_translate("MainWindow", "初始最小距离："))
        self.pursuer_num_lineedit.setText(_translate("MainWindow", "4"))
        self.exp_num_baseline_lineedit.setText(_translate("MainWindow", "100"))
        self.pursuers_num_baseline_label.setText(_translate("MainWindow", "追捕者数量："))
        self.exp_num_baseline_label.setText(_translate("MainWindow", "实验次数："))
        self.env_length_baseline_label.setText(_translate("MainWindow", "环境长："))
        self.exp_num_ablation_lineedit.setText(_translate("MainWindow", "100"))
        self.env_length_abaltion_label.setText(_translate("MainWindow", "环境长："))
        self.env_length_ablation_lineedit.setText(_translate("MainWindow", "60"))
        self.exp_num_ablation_label.setText(_translate("MainWindow", "实验次数："))
        self.env_width_ablation_lineedit.setText(_translate("MainWindow", "60"))
        self.pursuer_num_ablation_label.setText(_translate("MainWindow", "追捕者数量："))
        self.obs_num_ablation_label.setText(_translate("MainWindow", "障碍物数量："))
        self.init_min_dist_ablation_lineedit.setText(_translate("MainWindow", "15"))
        self.init_min_dist_ablation_label.setText(_translate("MainWindow", "初始最小距离："))
        self.env_width_ablation_label.setText(_translate("MainWindow", "环境宽："))
        self.obs_num_ablation_lineedit.setText(_translate("MainWindow", "2"))
        self.pursuer_num_ablation_lineedit_2.setText(_translate("MainWindow", "4"))
        self.ablation_apply_button.setText(_translate("MainWindow", "运行"))
        self.ablation_collision_button.setText(_translate("MainWindow", "碰撞率对比图"))
        self.ablation_time_button.setText(_translate("MainWindow", "时间对比图"))
        self.ablation_success_button.setText(_translate("MainWindow", "成功率对比图"))
        self.simulation_panel.setText(_translate("MainWindow", "仿真界面"))
        self.action_statistics_panel.setText(_translate("MainWindow", "动作统计界面"))
        self.baseline_compare_panel.setText(_translate("MainWindow", "基线比较界面"))
        self.ablation_experiment_panel.setText(_translate("MainWindow", "消融实验界面"))
from pyqtgraph import PlotWidget
